# Generated by Django 3.2.9 on 2021-12-09 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_btdelegationrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_delegacje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('saved', 'zapisany'), ('in_progress', 'w akceptacji'), ('approved', 'zaakceptowany'), ('rejected', 'odrzucony'), ('settlement_in_progress', 'W rozliczeniu'), ('settled', 'rozliczony'), ('canceled', 'anulowany')], max_length=30)),
                ('employee_level', models.CharField(choices=[('lvl1', 'podstawowy'), ('lvl2', 'kierownik'), ('lvl3', 'dyrektor'), ('lvl4', 'dyrektor regionu'), ('lvl5', 'dyrektor dywizji'), ('lvl6', 'członek zarządu'), ('lvl7', 'prezes zarządu')], max_length=30)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('trip_purpose_text', models.CharField(max_length=250)),
                ('transport_type', models.CharField(choices=[('default', ''), ('train', 'pociąg'), ('plane', 'samolot'), ('company_car', 'samochód służbowy'), ('own_car', 'własny samochód'), ('other', 'inny')], max_length=30)),
                ('travel_route', models.CharField(max_length=120)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('application_log', models.CharField(max_length=2400)),
                ('approval_date', models.CharField(blank=True, max_length=15, null=True)),
                ('CostCenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_applications', to='setup.btcostcenter')),
                ('advance_payment_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bt_applications', to='setup.btcurrency')),
                ('application_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_applications_author', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bt_approver', to=settings.AUTH_USER_MODEL)),
                ('bt_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_applications', to='setup.btcountry')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BtApplicationSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_status', models.CharField(choices=[('saved', 'zapisany'), ('in_progress', 'w akceptacji'), ('approved', 'zaakceptowany'), ('rejected', 'odrzucony'), ('settlement_in_progress', 'W rozliczeniu'), ('settled', 'rozliczony'), ('canceled', 'anulowany')], max_length=30)),
                ('bt_application_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bt_applications_settlements', to='e_delegacje.btapplication')),
            ],
        ),
        migrations.CreateModel(
            name='BtApplicationSettlementMileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_car_reg_number', models.CharField(max_length=8)),
                ('trip_start_place', models.CharField(max_length=50)),
                ('trip_date', models.DateField()),
                ('trip_description', models.CharField(max_length=120)),
                ('trip_purpose', models.CharField(max_length=240)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_agreement_signed', models.BooleanField(default=False)),
                ('bt_application_settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bt_application_settlement_mileages', to='e_delegacje.btapplicationsettlement')),
                ('bt_mileage_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_application_settlement_mileages', to='setup.btmileagerates')),
            ],
        ),
        migrations.CreateModel(
            name='BtApplicationSettlementInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_completed', models.CharField(choices=[('tak', 'tak'), ('nie', 'nie')], max_length=25)),
                ('bt_start_date', models.DateField(blank=True, null=True)),
                ('bt_start_time', models.TimeField(blank=True, null=True)),
                ('bt_end_date', models.DateField(blank=True, null=True)),
                ('bt_end_time', models.TimeField(blank=True, null=True)),
                ('settlement_exchange_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('settlement_log', models.CharField(max_length=2400)),
                ('advance_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bt_application_settlement_info', to='e_delegacje.btapplication')),
                ('bt_application_settlement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bt_application_info', to='e_delegacje.btapplicationsettlement')),
            ],
        ),
        migrations.CreateModel(
            name='BtApplicationSettlementFeeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_quantity', models.IntegerField()),
                ('dinner_quantity', models.IntegerField()),
                ('supper_quantity', models.IntegerField()),
                ('bt_application_settlement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bt_application_settlement_feeding', to='e_delegacje.btapplicationsettlement')),
            ],
        ),
        migrations.CreateModel(
            name='BtApplicationSettlementCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_cost_category', models.CharField(choices=[('accommodation', 'nocleg'), ('transport', 'dojazd'), ('luggage', 'bagaż'), ('other', 'inne')], max_length=40)),
                ('bt_cost_description', models.CharField(max_length=140)),
                ('bt_cost_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bt_cost_document_date', models.DateField()),
                ('bt_cost_VAT_rate', models.CharField(choices=[('W1', '23 %'), ('W8', '8 %'), ('WN', 'nie dotyczy'), ('W0', 'zwolniony')], max_length=20)),
                ('attachment', models.FileField(null=True, upload_to='')),
                ('bt_application_settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bt_application_settlement_costs', to='e_delegacje.btapplicationsettlement')),
                ('bt_cost_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_application_settlement_costs', to='setup.btcurrency')),
            ],
        ),
    ]
