# Generated by Django 3.2.12 on 2022-02-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0002_btapplication_btapplicationsettlement_btapplicationsettlementcost_btapplicationsettlementfeeding_bta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btapplicationsettlementcost',
            name='bt_cost_category',
            field=models.CharField(choices=[('accommodation', 'nocleg'), ('transport', 'dojazd'), ('luggage', 'bagaż'), ('consumption', 'konsumpcja')], max_length=40),
        ),
    ]
