# Generated by Django 3.2.12 on 2022-02-20 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_delegacje', '0003_alter_btapplicationsettlementcost_bt_cost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='btapplication',
            name='bt_company_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bt_applications', to='setup.btcompanycode'),
            preserve_default=False,
        ),
    ]
