# Generated by Django 3.2.9 on 2021-12-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtDelegationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delagation_rate', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
