# Generated by Django 3.1.7 on 2022-02-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('setup', '0003_auto_20220216_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
