# Generated by Django 3.2.12 on 2022-02-20 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('setup', '0005_auto_20220216_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btuser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.CreateModel(
            name='BtUserVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_users_vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
