# Generated by Django 3.2.12 on 2022-02-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20220220_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='btdelegationrate',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Bt_Delegationrates', to='setup.btcurrency'),
        ),
    ]
