# Generated by Django 3.2.12 on 2022-02-21 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_auto_20220220_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtUserAuthorisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_user_authorisations', to='setup.btcostcenter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bt_user_authorisations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
