# Generated by Django 3.2.12 on 2022-03-24 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_auto_20220321_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btorder',
            name='cost_center',
        ),
        migrations.AddField(
            model_name='btcostcenter',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bt_CostCenters', to='setup.btorder'),
        ),
    ]
